import{i as a,S as l}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const c="43843798-e4c61f3cfe0ada13281a73887",u="https://pixabay.com/api/",d=s=>{const t=new URLSearchParams({q:s,key:c,per_page:20,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${u}?${t}`).then(i=>{if(!i.ok)throw new Error("Network response was not ok");return i.json()})};function f(s){return s.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item" data-lightbox="gallery">
            <img src="${t.webformatURL}" alt="${t.tags}" />
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Likes</strong> ${t.likes}</li>
                <li class="list-group-item"><strong>Views</strong> ${t.views}</li>
                <li class="list-group-item"><strong>Comments</strong> ${t.comments}</li>
                <li class="list-group-item"><strong>Downloads</strong> ${t.downloads}</li>
              </ul>
            </div>
        </a>   
    `).join("")}document.addEventListener("DOMContentLoaded",function(){const s=document.querySelector(".js-search-form"),t=document.querySelector(".js-gallery"),i=document.querySelector(".js-loader");s.addEventListener("submit",function(n){n.preventDefault();const e=document.querySelector(".js-search-input"),o=e.value.trim();if(o===""){t.innerHTML="",e.value="",a.show({message:"Input field can not be empty",position:"topRight",timeout:2e3,color:"red"});return}t.innerHTML="",i.classList.remove("is-hidden"),d(o).then(r=>{r.totalHits===0?a.show({message:"Sorry, there are no images for this query",position:"topRight",timeout:2e3,color:"red"}):(t.innerHTML=f(r.hits),p())}).catch(r=>{console.error("Fetch error:",r),a.show({message:"Failed to load images",position:"topRight",timeout:2e3,color:"red"})}).finally(()=>{e.value="",i.classList.add("is-hidden")})})});function p(){new l(".gallery a",{overlayOpacity:1,captionsData:"alt",captionsDelay:250,nav:!0,close:!0,showCounter:!0,animationSpeed:300,fadeSpeed:300}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
