import{a as f,i as l,S as y}from"./assets/vendor-eded45c0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L="43843798-e4c61f3cfe0ada13281a73887",w="https://pixabay.com/api/",m=async(i,t=1)=>{const s=new URLSearchParams({q:i,key:L,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t});try{return(await f.get(`${w}?${s}`)).data}catch{throw new Error("Network response was not ok")}};function g(i){return i.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item" data-lightbox="gallery">
            <img src="${t.webformatURL}" alt="${t.tags}" />
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Likes</strong> ${t.likes}</li>
                <li class="list-group-item"><strong>Views</strong> ${t.views}</li>
                <li class="list-group-item"><strong>Comments</strong> ${t.comments}</li>
                <li class="list-group-item"><strong>Downloads</strong> ${t.downloads}</li>
              </ul>
            </div>
        </a>   
    `).join("")}let d=1,h="",u=0,c=0;document.addEventListener("DOMContentLoaded",function(){const i=document.querySelector(".js-search-form"),t=document.querySelector(".js-gallery"),s=document.querySelector(".js-loader"),r=document.querySelector(".js-load-more");if(!i||!t||!s||!r){console.error("One or more elements were not found in the DOM.");return}i.addEventListener("submit",async function(e){e.preventDefault();const o=document.querySelector(".js-search-input"),n=o.value.trim();if(n===""){t.innerHTML="",o.value="",l.show({message:"Input field can not be empty",position:"topRight",timeout:2e3,color:"red"});return}t.innerHTML="",s.classList.remove("is-hidden"),r.classList.add("is-hidden"),d=1,h=n,c=0;try{const a=await m(h,d);u=a.totalHits,c+=a.hits.length,u===0?l.show({message:"Sorry, there are no images for this query",position:"topRight",timeout:2e3,color:"red"}):(t.innerHTML=g(a.hits),p(),c<u&&r.classList.remove("is-hidden"))}catch(a){console.error("Fetch error:",a),l.show({message:"Failed to load images",position:"topRight",timeout:2e3,color:"red"})}finally{o.value="",s.classList.add("is-hidden")}}),r.addEventListener("click",async function(){d+=1,s.classList.remove("is-hidden"),r.classList.add("is-hidden");try{const e=await m(h,d);c+=e.hits.length,t.insertAdjacentHTML("beforeend",g(e.hits)),p();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),c<u?r.classList.remove("is-hidden"):l.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,color:"blue"})}catch(e){console.error("Fetch error:",e),l.show({message:"Failed to load more images",position:"topRight",timeout:2e3,color:"red"})}finally{s.classList.add("is-hidden")}})});function p(){new y(".gallery a",{overlayOpacity:1,captionsData:"alt",captionsDelay:250,nav:!0,close:!0,showCounter:!0,animationSpeed:300,fadeSpeed:300}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
